- hosts: workstation

  tasks:
    - name: 'download atom'
      sudo: no
      get_url: url=https://atom.io/download/deb
        dest=/opt/battleschool/downloads/
  
    - name: 'install atom'
      sudo: yes
      apt: deb=/opt/battleschool/downloads/atom-amd64.deb

    - name: 'install packages'
      sudo: no
      command: apm install {{ item }}
      with_items:
        - language-ansible
        - file-watcher
        - gitignore-snippets
        - language-chef
        - language-gitignore
        - language-varnish
        - linter-clang
        - linter-foodcritic
        - linter-pep257
        - linter-pep8
        - linter-pylint
        - linter-ruby
        - linter-tidy
        - minimap
        - wakatime
        - python-autopep8        
