- hosts: workstation
  tasks:
    - name: 'download atom'
      sudo: no
      get_url: url=https://atom.io/download/deb
        dest=~/.ansible/downloads/
  
    - name: 'install atom'
      sudo: yes
      apt: deb=~/.ansible/downloads/atom-amd64.deb
      
    - name: 'install atom packages playbook'
      sudo: no
      shell: ansible-galaxy install jgkim.atom
        
    - name: 'install atom packages'
      sudo: no
      vars:
        atom_upgrade_all: True
      atom_packages:
      - language-ansible
      - file-watcher
      - gitignore-snippets
      - language-chef
      - language-gitignore
      - language-varnish
      - linter-clang
      - linter-foodcritic
      - linter-pep257
      - linter-pep8
      - linter-pylint
      - linter-ruby
      - linter-tidy
      - minimap
      - wakatime
      - python-autopep8
