- hosts: workstation
  tasks:
    - name: 'download atom'
      get_url: url=https://atom.io/download/deb
        dest=/tmp/
  
    - name: 'install atom'
      sudo: yes
      apt: deb=/tmp/atom-amd64.deb 
