---
- hosts: workstation

  tasks:    
    - name: 'create download folder'
      sudo: no
      file: path=~/.ansible/downloads/ state=directory mode=0755 owner=andor group=andor

    - name: 'create logz folder'
      sudo: no
      file: path=~/.ansible/logz/ state=directory mode=0755 owner=andor group=andor

