---
- hosts: workstation

  tasks:    
    - name: 'create download folder'
      sudo: yes
      file: path=/opt/battleschool/downloads/ state=directory mode=0755 owner=andor group=andor

    - name: 'create logz folder'
      sudo: yes
      file: path=/opt/battleschool/logz/ state=directory mode=0755 owner=andor group=andor

