- hosts: workstation
  tasks:
    - name: 'download chrome'
      sudo: no
      get_url: url=https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dest=/opt/battleschool/downloads/
  
    - name: 'install chrome'
      sudo: yes
      apt: deb=/opt/battleschool/downloads/google-chrome-stable_current_amd64.deb
