---
cache_dir: ~/.battleschool/cache


sources:
  #url:
  #  - name: andor.yml
  #    url: https://raw.githubusercontent.com/brianchoate/ansible-private/master/andor.yml?token=AAmBy2rr5SfJN53U_kbQ__bAqPV9FamLks5WfyFdwA%3D%3D

  git:
   - name: 'ubuntu1510'
     repo: 'https://github.com/brianchoate/ansible-ubuntu'
     playbooks:
          - chrome.yml
  #        - github.yml
  #        - aws.yml
  #        - atom.yml
  #        - chome.yml
  #        - mypy.yml
  #           flake8, pep8, pep256, yaph, virtualenvwrapper
  #        - zsh.yml
  #           oh-my-zsh
  #        - tools
  #           icdiff, ack, http, powerline
