---
- hosts: workstation

  tasks:
    - name: create homdir symlinks
      file: src={{item.from}} dest={{item.to}} state=link
      sudo: no
      with_items:
         - from: ~/conf/gitconfig.wikia
           to: ~/.gitconfig
         - from: ~/conf/screenrc
           to: ~/.screenrc
         - from: ~/conf/ssh.config.wikia
           to: ~/.ssh/config
         - from: ~/conf/vimrc_amix_basic
           to: ~/.vimrc
         - from: ~/conf/bash/bash_profile_wikia_mbp
           to: ~/.bash_profile

    - name: mkdir backup dirs location
      sudo: no
      file: path=~/.backups/org_dirs/ state=directory recurse=yes

    - name: backup dirs
      sudo: yes 
      command: mv ~/{{item}} ~/.backups/org_dirs/
      with_items:
        - Applications
        - Documents
        - Movies
        - Music
        - Pictures
        - Desktop
        - Library

    - name: create homdir symlinks
      file: src={{item.from}} dest={{item.to}} state=link
      sudo: no
      with_items:
        - from: '~/Google%20Drive/Applications'
          to: ~/Applications/
        - from: '~/Google%20Drive/Documents'
          to: ~/Documents
        - from: '~/Google%20Drive/Movies'
          to: ~/Movies
        - from: '~/Google%20Drive/Music'
          to: ~/Music
        - from: '~/Google%20Drive/Pictures'
          to: ~/Pictures
        - from: '~/Google%20Drive/Desktop'
          to: ~/Desktop
        - from: '~/Google%20Drive/Library'
          to: ~/Library
