- hosts: workstation

  tasks:
    - name: 'download lastpass'
      sudo: no
      get_url: url=http://lastpass.com/lplinux.tar.bz2
        dest=/opt/battleschool/downloads/

    - name: 'Unarchive lastpass'
      sudo: no
      unarchive: src=/opt/battleschool/downloads/lplinux.tar.bz2
        dest=/opt/battleschool/downloads/lplinux

    - name: 'install lastpass'
      sudo: yes
      command: /opt/battleschool/downloads/lplinux

# Unarchive a file that needs to be downloaded (added in 2.0)
