- hosts: workstation

  tasks:
    # 1. Add the Spotify repository signing key
    #    to be able to verify downloaded packages
    - name: 'add spotify apt key'
      sudo: yes
      apt_key:
        keyserver=keyserver.ubuntu.com
        id=BBEBDCB318AD50EC6865090613B00F1FD2C19886

    # 2. Add the Spotify repository
    - name: 'add spotify repo'
      sudo: yes
      apt_repository: repo='deb http://repository.spotify.com stable non-free'
        update_cache=yes

    - name: 'install spotify'
      sudo: yes
      apt: name=spotify-client
