- hosts: workstation
  tasks:
    - name: 'install apt packages'
      sudo: yes
      apt: name={{ item }}
      with_items:
        - ack-grep
        - httpie
        - pylint
        - pylint3
        - pep8
        - pep257
        - gnome-do
        - xfwm4-themes
        - virt-manager
        - virtualbox
        - virtualbox-guest-additions-iso
        - virtualbox-ext-pack
        - lxc
        - lxc-templates
        
    - name: 'install pip packages'
      sudo: no
      pip: name={{ item }} extra_args='--user'
      with_items:
        - flake8
        - powerline-status
        - yapf
