- hosts: workstation

  tasks:
    - name: 'download tresorit'
      sudo: no
      get_url: url=https://installerstorage.blob.core.windows.net/public/install/tresorit_installer.run
        dest=/opt/battleschool/downloads/

    - name: 'chmod tresorit'
      sudo: no
      file: path=/opt/battleschool/downloads/tresorit_installer.run mode="0755"

    - name: 'install tresorit'
      sudo: yes
      command: /opt/battleschool/downloads/tresorit_installer.run
        chdir=/opt/battleschool/downloads/


# Unarchive a file that needs to be downloaded (added in 2.0)
