- hosts: workstation

  tasks:
    - name: 'download installer'
      sudo: no
      get_url: url=https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh
        dest=/opt/battleschool/downloads/oh-my-zsh-installer.sh
        
    - name: 'set execute'
      sudo: no
      file: path=/opt/battleschool/downloads/oh-my-zsh-installer.sh owner=andor group=andor mode=0755
      
    - name: 'install oh-my-zsh'
      sudo: no
      command:  /bin/sh -c /opt/battleschool/downloads/oh-my-zsh-installer.sh
        creates=~/.oh-my-zsh
      
    - name: 'remove .zshrc'
      sudo: no
      file: state=absent path=~/.zshrc
      
    - name: 'Link .zshrc'
      sudo: no
      file: state=link src=~/conf/zsh/zshrc dest=~/.zshrc
